CREATE TABLE IF NOT EXISTS accounts (
    id INT(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS pdfs (
    idPDF INT(11) NOT NULL AUTO_INCREMENT,
    nombrePdf VARCHAR(50) NOT NULL,
    pdfData MEDIUMBLOB NOT NULL,
    idUser INT(11) NOT NULL,
    PRIMARY KEY (idPDF),
    FOREIGN KEY (idUser) REFERENCES accounts(id)
);